[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

# Force clean build
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

# Cache Control
[build.processing.cache]
  skip_processing = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
